// <auto-generated />
using System;
using MealMate.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MealMate.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816150733_AddReviewFieldsToMeals")]
    partial class AddReviewFieldsToMeals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("MealMate.Api.Models.AgentAdvance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<decimal>("AdvanceTaken")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DailyDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsFullyRepaid")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("TotalDeducted")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("AgentAdvances");
                });

            modelBuilder.Entity("MealMate.Api.Models.AgentPayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("AgentPayouts");
                });

            modelBuilder.Entity("MealMate.Api.Models.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<Guid>("MealId")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MealId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("MealMate.Api.Models.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("Allergens")
                        .HasColumnType("longtext");

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<int>("Carbs")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("Fat")
                        .HasColumnType("int");

                    b.Property<int>("Fiber")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Ingredients")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsVeg")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PortionSize")
                        .HasColumnType("longtext");

                    b.Property<string>("PrepTime")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Protein")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("double");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<string>("ReviewsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("SpiceLevel")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AgentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Allergens = "",
                            Calories = 0,
                            Carbs = 0,
                            Category = "Thali",
                            Description = "Creamy black lentils",
                            Fat = 0,
                            Fiber = 0,
                            ImageUrl = "assets/meals/dal_makhani.jpg",
                            Ingredients = "",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Dal Makhani",
                            PortionSize = "350g",
                            PrepTime = "25 min",
                            Price = 180m,
                            Protein = 0,
                            Rating = 4.7999999999999998,
                            ReviewCount = 0,
                            ReviewsJson = "[]",
                            SpiceLevel = "Medium"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            AgentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Allergens = "",
                            Calories = 0,
                            Carbs = 0,
                            Category = "Fast Food",
                            Description = "Grilled cottage cheese",
                            Fat = 0,
                            Fiber = 0,
                            ImageUrl = "assets/meals/paneer_tikka.jpg",
                            Ingredients = "",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Paneer Tikka",
                            PortionSize = "350g",
                            PrepTime = "25 min",
                            Price = 220m,
                            Protein = 0,
                            Rating = 4.7999999999999998,
                            ReviewCount = 0,
                            ReviewsJson = "[]",
                            SpiceLevel = "Medium"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            AgentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Allergens = "",
                            Calories = 0,
                            Carbs = 0,
                            Category = "Thali",
                            Description = "Fragrant rice with vegetables",
                            Fat = 0,
                            Fiber = 0,
                            ImageUrl = "assets/meals/veg_pulao.jpg",
                            Ingredients = "",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Veg Pulao",
                            PortionSize = "350g",
                            PrepTime = "25 min",
                            Price = 150m,
                            Protein = 0,
                            Rating = 4.7999999999999998,
                            ReviewCount = 0,
                            ReviewsJson = "[]",
                            SpiceLevel = "Medium"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            AgentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Allergens = "",
                            Calories = 0,
                            Carbs = 0,
                            Category = "Fast Food",
                            Description = "Crispy crepe with potato filling",
                            Fat = 0,
                            Fiber = 0,
                            ImageUrl = "assets/meals/masala_dosa.jpg",
                            Ingredients = "",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Masala Dosa",
                            PortionSize = "350g",
                            PrepTime = "25 min",
                            Price = 120m,
                            Protein = 0,
                            Rating = 4.7999999999999998,
                            ReviewCount = 0,
                            ReviewsJson = "[]",
                            SpiceLevel = "Medium"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            AgentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Allergens = "",
                            Calories = 0,
                            Carbs = 0,
                            Category = "Drinks",
                            Description = "Refreshing yogurt drink",
                            Fat = 0,
                            Fiber = 0,
                            ImageUrl = "assets/meals/mango_lassi.jpg",
                            Ingredients = "",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Mango Lassi",
                            PortionSize = "350g",
                            PrepTime = "25 min",
                            Price = 80m,
                            Protein = 0,
                            Rating = 4.7999999999999998,
                            ReviewCount = 0,
                            ReviewsJson = "[]",
                            SpiceLevel = "Medium"
                        });
                });

            modelBuilder.Entity("MealMate.Api.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<decimal>("CreditUsedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CustomMealDetails")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsCustomMeal")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OrderNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("int");

                    b.Property<int>("PointsRedeemed")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WalletAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MealMate.Api.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<Guid>("MealId")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MealMate.Api.Models.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentDay")
                        .HasColumnType("int");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<decimal>("DailyDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Months")
                        .HasColumnType("int");

                    b.Property<string>("PlanName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TotalDays")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("MealMate.Api.Models.SubscriptionPausedDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<DateTime>("PausedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_bin");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubscriptionPausedDays");
                });

            modelBuilder.Entity("MealMate.Api.Models.SubscriptionRotationMeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<Guid>("MealId")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceAtSubscription")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_bin");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubscriptionRotationMeals");
                });

            modelBuilder.Entity("MealMate.Api.Models.SubscriptionSkippedDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<DateTime>("SkippedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_bin");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubscriptionSkippedDays");
                });

            modelBuilder.Entity("MealMate.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CreditUsed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<string>("KitchenName")
                        .HasColumnType("longtext");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("ServiceRadiusKm")
                        .HasColumnType("double");

                    b.Property<decimal>("WalletBalance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Address = "Connaught Place, New Delhi",
                            CreatedAt = new DateTime(2026, 8, 16, 15, 7, 32, 574, DateTimeKind.Utc).AddTicks(9355),
                            CreditLimit = 500m,
                            CreditUsed = 0m,
                            Email = "agent@mealmate.com",
                            FullName = "Default Chef",
                            KitchenName = "Grand Central Kitchen",
                            Latitude = 28.613900000000001,
                            Longitude = 77.209000000000003,
                            LoyaltyPoints = 1000,
                            PhoneNumber = "1234567890",
                            Role = "Agent",
                            ServiceRadiusKm = 20.0,
                            WalletBalance = 2500m
                        });
                });

            modelBuilder.Entity("MealMate.Api.Models.AgentAdvance", b =>
                {
                    b.HasOne("MealMate.Api.Models.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("MealMate.Api.Models.AgentPayout", b =>
                {
                    b.HasOne("MealMate.Api.Models.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("MealMate.Api.Models.CartItem", b =>
                {
                    b.HasOne("MealMate.Api.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealMate.Api.Models.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("MealMate.Api.Models.Meal", b =>
                {
                    b.HasOne("MealMate.Api.Models.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("MealMate.Api.Models.Order", b =>
                {
                    b.HasOne("MealMate.Api.Models.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealMate.Api.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MealMate.Api.Models.OrderItem", b =>
                {
                    b.HasOne("MealMate.Api.Models.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealMate.Api.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MealMate.Api.Models.Subscription", b =>
                {
                    b.HasOne("MealMate.Api.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MealMate.Api.Models.SubscriptionPausedDay", b =>
                {
                    b.HasOne("MealMate.Api.Models.Subscription", "Subscription")
                        .WithMany("PausedDays")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("MealMate.Api.Models.SubscriptionRotationMeal", b =>
                {
                    b.HasOne("MealMate.Api.Models.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealMate.Api.Models.Subscription", "Subscription")
                        .WithMany("RotationMeals")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("MealMate.Api.Models.SubscriptionSkippedDay", b =>
                {
                    b.HasOne("MealMate.Api.Models.Subscription", "Subscription")
                        .WithMany("SkippedDays")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("MealMate.Api.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MealMate.Api.Models.Subscription", b =>
                {
                    b.Navigation("PausedDays");

                    b.Navigation("RotationMeals");

                    b.Navigation("SkippedDays");
                });
#pragma warning restore 612, 618
        }
    }
}
